apiVersion: v1
kind: Service
metadata:
  name: keit
  labels:
    app: keit
  annotations:
    goway-service: "true"
spec:
  type: NodePort
  ports:
  - port: 80
    name: http
  selector:
    app: keit
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: keit-v1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: keit
        version: v1
    spec:
      containers:
      - name: keit
        image: andrepinto/keit-envoy:1.0.1 
        resources:
          requests:
            cpu: "100m"
        imagePullPolicy: IfNotPresent #Always
        ports:
        - containerPort: 80
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: keit-v2
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: keit
        version: v2
    spec:
      containers:
      - name: keit
        image: andrepinto/keit-envoy:2.0.1
        resources:
          requests:
            cpu: "100m"
        imagePullPolicy: IfNotPresent #Always
        ports:
        - containerPort: 80
---
