apiVersion: v1
kind: Service
metadata:
  name: keit
  labels:
    app: keit
  annotations:
    goway-service: "true"
spec:
  type: NodePort
  ports:
  - port: 3000
    name: http
  selector:
    app: keit
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: keit-v1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: keit
        version: v1
    spec:
      containers:
      - name: keit
        image: andrepinto/keit:1.0.1
        resources:
          requests:
            cpu: "100m"
        imagePullPolicy: IfNotPresent #Always
        ports:
        - containerPort: 3000
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: keit-v2
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: keit
        version: v2
    spec:
      containers:
      - name: keit
        image: andrepinto/keit:2.0.1
        resources:
          requests:
            cpu: "100m"
        imagePullPolicy: IfNotPresent #Always
        ports:
        - containerPort: 3000
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: keit
spec:
  rules:
  - http:
      paths:
      - path: /api
        backend:
          serviceName: keit
          servicePort: 3000
---
